source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JRMFloatingAnimation_Example', :exclusive => true do
  pod 'JRMFloatingAnimation', :path => '../'
end

target 'JRMFloatingAnimation_Tests', :exclusive => true do
  pod 'JRMFloatingAnimation', :path => '../'

  
end
